#!/bin/bash

LOCKFILE=/var/run/logtail-logster.parsers.HaProxyLogster.HaProxyLogster-var-log-haproxy.log.lock
STATEFILE=/var/run/logtail-logster.parsers.HaProxyLogster.HaProxyLogster-var-log-haproxy.log.state

# pull this from the default file
unset GRAPHITE_HOST_PORT
unset STATSD_HOST_PORT
unset HAPROXY_SOCKET
unset REQUEST_HEADERS
unset CRAWLERHOSTS
unset ISSUUDOCS
unset USE_XFF_AS_CLIENTIP

test -f /etc/default/logster-haproxy-graphite && . /etc/default/logster-haproxy-graphite

if [ \( -z "${GRAPHITE_HOST_PORT}" -a -z "${STATSD_HOST_PORT}" \) -o -z "${HAPROXY_SOCKET}" ]; then
    echo 'Please set either ${GRAPHITE_HOST_PORT} or ${STATSD_HOST_PORT} and ${HAPROXY_SOCKET}'
    echo 'See /etc/default/logster-haproxy-graphite'
    exit 1
fi

unset REQUEST_HEADERS_OPTION
if [ -n "${REQUEST_HEADERS}" ]; then
    REQUEST_HEADERS_OPTION=" --headers ${REQUEST_HEADERS}"
fi

unset CRAWLERHOSTS_OPTION
if [ -n "${CRAWLERHOSTS}" ]; then
    CRAWLERHOSTS_OPTION=" --crawlerhosts ${CRAWLERHOSTS}"
fi

unset ISSUUDOCS_OPTION
if [ -n "${ISSUUDOCS}" ]; then
    ISSUUDOCS_OPTION=" --issuudocs"
fi

unset USE_XFF_AS_CLIENTIP_OPTION
if [ -n "${USE_XFF_AS_CLIENTIP}" ]; then
    USE_XFF_AS_CLIENTIP_OPTION=" --xffip"
fi

LOGDIR=/var/log/logster/
test -d ${LOGDIR} || mkdir -p ${LOGDIR}

# Check if another is already running
if [ -e "${LOCKFILE}" ]; then
    A=$(stat --format=%Y ${LOCKFILE})
    B=$(date +%s)
    D=$(expr $B - $A)
    if [ $D -gt 200 ]; then
        pkill -f 'perl.*logtail2'; sleep 20
        pkill -f 'python.*logster'; sleep 10
        [ -e "${STATEFILE}" ] && rm -f ${STATEFILE}
        [ -e "${LOCKFILE}"  ] && rm -f ${LOCKFILE}
        exit 0
    else
        exit 0
    fi
fi

if [ -n "${STATSD_HOST_PORT}" ]; then
    logster --output statsd \
        --statsd-host ${STATSD_HOST_PORT} \
        --parser-options "--socket ${HAPROXY_SOCKET}${CRAWLERHOSTS_OPTION}${REQUEST_HEADERS_OPTION}${ISSUUDOCS_OPTION}${USE_XFF_AS_CLIENTIP_OPTION}" \
        HaProxyLogster \
        /var/log/haproxy.log
else
    logster --output graphite \
        --graphite-host ${GRAPHITE_HOST_PORT} \
        --parser-options "--socket ${HAPROXY_SOCKET}${CRAWLERHOSTS_OPTION}${REQUEST_HEADERS_OPTION}${ISSUUDOCS_OPTION}${USE_XFF_AS_CLIENTIP_OPTION}" \
        HaProxyLogster \
        /var/log/haproxy.log
fi

