#!/usr/bin/bash

# pull this from default file
GRAPHITE_HOST_PORT=

test -f /etc/default/logster-haproxy-graphite && . /etc/default/logster-haproxy-graphite

if [ -z "$GRAPHITE_HOST_PORT" ]; then
    exit
fi

LOGDIR=/var/log/logster/
test -d ${LOGDIR} || mkdir -p ${LOGDIR}

logster --output graphite \
	--graphite-host ${GRAPHITE_HOST_PORT} \
	HaProxyLogster \
    /var/log/haproxy.log
